In [1]:
# Donchian Weekly Trend Following System
import numpy as np
import pandas as pd

In [2]:
# Function definitions.
def donchian(prices, period):
    '''Calculate upper, lower, & middle Donchian lines.'''
    df = pd.DataFrame(prices.copy())
    df['upr'] = df.high.rolling(period).max().shift(periods=1)
    df['lwr'] = df.low.rolling(period).min().shift(periods=1)
    df['mid'] = 0.5 * (df.upr + df.lwr)
    return df


def remainder_zero(series, divisor):
    '''Increment number until remainder is zero.'''
    def increment_dividend(dividend, divisor):
        '''Increment dividend while remainder does not equal zero.'''
        while dividend % divisor != 0:
            dividend += 1
        return dividend
    series = series.map(lambda x: increment_dividend(x, divisor))
    return series


def weekly(exchange, tidm):
    '''Generate weekly prices from SharePad csv file of daily prices.'''
    df = pd.read_csv(
        f'{exchange}_{tidm}_prices.csv',
        header=0,
        names=['date', 'open', 'high', 'low', 'close'],
        index_col=0,
        usecols=[0, 1, 2, 3, 4],
        parse_dates=True,
        dayfirst=True,
    )
    df = df.sort_index()
    functions = dict(open='first', high='max', low='min', close='last')
    df = df.resample('W-FRI').agg(functions)
    df = df / 100
    return df

In [3]:
# Trade parameters.
exchange = 'LSE'
tidm = 'HSV'
periods = [48, 24, 12, 6]  # System look back periods.
position_size = 7500  # Position size in major currency unit.
risk_pct = 0.2  # Percentage risk per trade.
commission = 11.95  # Commission per trade.
sduty = 0.5  # Stamp Duty percentage.

In [4]:
# Import weekly prices.
prices = weekly(exchange, tidm)

In [5]:
# Trade signals.
signals = []
for sys, period in enumerate(periods):
    # Donchian channel.
    dc = donchian(prices, period)
    dc['sys'] = sys
    dc['period'] = period
    
    # Raw entry & exit signals.
    if sys == 0:
        dc['entry'] = np.where(dc.close > dc.upr, 1, 0)
    else:
        dc['entry'] = buy
    dc['exit'] = np.where(dc.close < dc.mid, 1, 0)
    
    # State variable.
    dc['state'] = 0
    for i in range(period, len(dc)):
        if dc.loc[dc.index[i], 'entry'] == 1 and dc.loc[dc.index[i - 1], 'state'] == 0:
            dc.loc[dc.index[i], 'state'] = 1
        elif dc.loc[dc.index[i], 'exit'] == 1:
            dc.loc[dc.index[i], 'state'] = 0
        else:
            dc.loc[dc.index[i], 'state'] = dc.loc[dc.index[i - 1], 'state']
            
    # Buy & sell signals.
    dc['buy'] = np.where(np.logical_and(dc.state == 1, dc.state.shift(periods=1) == 0), 1, 0)
    buy = dc.buy
    dc['sell'] = np.where(np.logical_and(dc.state == 0, dc.state.shift(periods=1) == 1), 1, 0)
    
    signals.append(dc)

In [6]:
# Trade lists.
trades = []
for signal in signals:
    ts = pd.concat([signals[0][signals[0].buy == 1], signal[signal.sell == 1]])
    ts = ts.sort_index()
    trades.append(ts)

In [7]:
# Position size.
for trade in trades:
    # Buy side.
    trade['volatility'] = np.where(trade.buy == 1, abs((trade.mid - trade.close) / trade.close), 0)
    trade['risk_amt'] = np.where(trade.buy == 1, ((position_size * risk_pct) / trade.volatility), 0)
    trade['shares'] = np.where(trade.buy == 1, (trade.risk_amt / trade.close).astype('int'), 0)
    trade['shares_adj'] = remainder_zero(trade.shares, len(periods)) # Adjust shares to be divisible by number of systems.
    trade['risk_adj'] = trade.close * trade.shares_adj # Adjust risk amount for revised share count.
    
    # Sell side.
    for index, row in trade.iterrows():
        if row['buy'] == 1:
            shares_adj = row['shares_adj']
        elif row['sell'] == 1:
            trade.at[index, 'shares_adj'] = int(shares_adj / 4)

In [8]:
(
    trades[0].style
        .format_index(lambda s: s.strftime("%Y-%m-%d"))
        .format({
            'open': '{:.3f}',
            'high': '{:.3f}',
            'low': '{:.3f}',
            'close': '{:.3f}',
            'upr': '{:.3f}',
            'lwr': '{:.3f}',
            'mid': '{:.3f}',
            'volatility': '{:.1%}',
            'risk_amt': '{:,.2f}',
            'risk_adj': '{:,.2f}',
        })
)